sudo: false
language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6.5
install:
  - pip install tox tox-travis
  - pip install coverage coveralls
  - pip install ccxt

ibefore_install:
  - openssl aes-256-cbc -K $encrypted_b6cbb0f706c0_key -iv $encrypted_b6cbb0f706c0_iv -in setup.py.enc -out setup.py -d
  - tar xvf secrets.tar

script:
  - ls
  - python --version
  - python sample_a.py 
  - python -m unittest
 
env:
  global:
      # travis encrypt VAR1=foo VAR2=baz
      secure: "oDUAQEgORlfihp9Cdo7NvwWHEaIAEGfhp3IZVOU7x6gOq3ntNfwgrBDGTZQMGzlZ35mpl1j3OdI0Z4GwxZHvfTyk1r1YujJDzINwANcJNQKhAJ043bzda3++moOAkU/OC3QSmP1jGx8Z+GTH5b9rl8zVTQCJLCNclSlZZRPZlB4+KqPNA29QZPwrVwwY3Gxqq1vG3ET+uo1y/H4OB7ntNYRpMRs5a/Hdv391aeKaesPFXEndHOJtP9p9fU7+boK/toFJYHSj4d9wKG1K2KhkwpzfrxHh/Nk5Pi/rKcADZbuue2+bA0O2Feu6viSlb7pofihfuXkbMmwMjBdveWse4r6c9udUvzIN2MQ9HrKKgldO62E5rhwjB0mHu4mfX7F6jQ20vKsnP34vgGc3DM3HWEWcPoql/Hqdq6bbxVI4e5vqKkH/klkTxx1irpIUxKY5jZ0eVg7YED+KDxiuPL7hPbt95Lv9YdmEJCcqG/Yw73UU7dgaqFvurzWSeAfAgu//8Oh8A1g7pqtECBBv8VxvwCWMvEVUxg/i9IivA/UJal2CCpzMD0jSfXjEEhhOp/bvk4avSeqHmRcXaTngrG/AQRY8kqddubFP2TpfFbhOuNXPEER8ODFzO0h7Ytte9UEX4XhWZsE2EcvRgG6uOYX+LO0nXAfcNAP299voUzMNSXU="`:WQ:


